### ISSUE TITLE
server side script

### ISSUE THREAD

**Issue by krodelabestiole** [chfritz/typhone#9]
hello, thanks for this app that looks (and works) great !

i was wondering though : can we get access to the server-side script ? and eventually install it on our own server ? e.g. is it all only html+js, and we could just download it and put it anywhere ? 
i confess i don't feel comfortable with the idea of forwarding all this data through a third service...

**Comment by chfritz** [comment]
Sure, it's all there. If you know meteor it should be easy-ish to deploy on
your own server.

Christian

(sent from my phone)
